# Generated by Django 5.0.4 on 2024-04-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=356)),
                ('endereco', models.CharField(max_length=500)),
                ('telefone', models.CharField(max_length=20)),
                ('link_catalogo', models.URLField(blank=True, null=True)),
                ('informacoes_adicionais', models.TextField(blank=True, max_length=2000, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
